Telecom.WebUI/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lib.AspNetCore.Mvc.JqGrid.Core.Request;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Telecom.Application;
using Telecom.Application.Interfaces;
using Telecom.Application.ViewModels;

namespace Telecom.WebUI.Controllers
{
    public class InvoiceController : Controller
    {
        IInvoicGeneration _invoicGeneration;
        InvoicingFlag InvoicingFlag = null;
        ILogonTab _logonTab;
        public InvoiceController(ILogonTab logonTab, IInvoicGeneration invoicGeneration)
        {
            _logonTab = logonTab;
            _invoicGeneration = invoicGeneration;
        }

        [AcceptVerbs("GET")]
        public IActionResult Index()
        {
            string userName = HttpContext.Session.GetString("UserName");
            string databaseName = HttpContext.Session.GetString("Database_Name");

            InvoicingSelectionViewModel invoicingSelectionViewModel = new InvoicingSelectionViewModel();
            try
            {
                InvoicingFlag=_invoicGeneration.GetFlagQuery(StaticConstItems.InvoicingFlag, databaseName);
                if (InvoicingFlag.FlagStatus)
                {
                    ViewBag.InvoiceStatus = "Task is not permitted while invoicing is busy by user: " + InvoicingFlag.UserName;
                }
                else
                {
                    InvoicingFlag = _invoicGeneration.GetFlagQuery(StaticConstItems.GenerateRemindersFlag, databaseName);
                    if (InvoicingFlag.FlagStatus)
                    {
                        ViewBag.InvoiceStatus = "Task is not permitted while invoicing is busy by user: " + InvoicingFlag.UserName;
                    }
                }
                _invoicGeneration.UpdateFlagQuery(StaticConstItems.InvoicingFlag,0,databaseName);
                 float VAT = Convert.ToSingle(_logonTab.GetServerIniDataQuery(StaticConstItems.IniDefaultVATPercentage,
                    StaticConstItems.DefaultVAT.ToString(), databaseName));

                //------------------View all companies-----------------------------------------------
                IList<SelectListItem> companies =_invoicGeneration.ViewCompanyQuery(0, databaseName);
                companies.Insert(0, new SelectListItem() { Value="", Text=""});
                invoicingSelectionViewModel.Company = companies;
                
                //------------------------------Pricing----------------------------------------------
                IList<SelectListItem> invoice = _invoicGeneration.ViewInvoicePrintTypeQuery(0, databaseName);
                invoicingSelectionViewModel.InvoiceOption = invoice;

                
            }
            catch (Exception ex)
            {

            }
            List<string> invoiceType = new List<string>()
            {
                "Invoicing","Split biling"
            };

            invoicingSelectionViewModel.Action = new List<string>() { "Check", "Uncheck" };
            invoicingSelectionViewModel.InvoiceType=invoiceType;
            invoicingSelectionViewModel.BillingCycle = 23;
            invoicingSelectionViewModel.InvoiceDate = DateTime.Now.Date;
            return View(invoicingSelectionViewModel);
            

        }

        [HttpGet]
        public PartialViewResult GetInvoice(string companyName,bool checkRecurringInvoice,string billingCycle,
            bool chbExcludeMobile)
        {
            string userName = HttpContext.Session.GetString("UserName");
            string databaseName = HttpContext.Session.GetString("Database_Name");

            //---------------------------Getting data for invocing----------------------//
            string companyNbr=_invoicGeneration.GetCompanyNbrQuery(companyName, databaseName);
            CompanyDetails companyDetails = _invoicGeneration.GetCompanyQuery(Convert.ToInt32(companyNbr), 
                    databaseName);

            //invoicingSelectionViewModel.AutoAcAutoAssignPayment =--Checkbox status chang
            int startDay = companyDetails.StartInvoiceDay;
            string printTypeDisc = companyDetails.PrintTypeDescription;
            int i = 0;
            if (chbExcludeMobile)
                i = 1;
            DateTime? dMaxDate = DateTime.Parse("2030-01-01");
            int n = 0;
            if (checkRecurringInvoice)
                n = 2;
            dMaxDate = null;
            List<InvoiceGrid> invoiceGrids= _invoicGeneration.GetAddressForInvoicingQuery(companyName,dMaxDate.ToString(),i,n, billingCycle,databaseName);

            foreach(InvoiceGrid invoice in invoiceGrids)
            {
                
                if (n == 2)
                {

                }
            }
            //JqGridRequest jqGridRequest = new JqGridRequest();
            return PartialView(@"~/Views/Invoice/InvoiceTab/_InvoiceGrid.cshtml",invoiceGrids);
        }

        [AcceptVerbs("POST")]
        public IActionResult GridData(JqGridRequest request,int ? rowId)
        {
            //IQueryable<InvoiceGrid> charactersQueryable = (rowId.HasValue) ? StarWarsContext.Characters.AsQueryable().Where(character => character.HomeworldId == rowId.Value) : StarWarsContext.Characters.AsQueryable();
            //charactersQueryable = FilterCharacters(charactersQueryable, request);

            //int totalRecords = charactersQueryable.Count();

            //JqGridResponse response = new JqGridResponse()
            //{
            //    TotalPagesCount = (int)Math.Ceiling((float)totalRecords / (float)request.RecordsCount),
            //    PageIndex = request.PageIndex,
            //    TotalRecordsCount = totalRecords,
            //    UserData = new
            //    {
            //        Name = "Averages:",
            //        Height = StarWarsContext.Characters.Average(character => character.Height),
            //        Weight = StarWarsContext.Characters.Average(character => character.Weight)
            //    }
            //};

            //charactersQueryable = SortCharacters(charactersQueryable, request.SortingName, request.SortingOrder);

            //foreach (InvoiceGrid invoiceGrid in charactersQueryable.Skip(request.PageIndex * request.RecordsCount).Take(request.PagesCount * request.RecordsCount))
            //{
            //    response.Records.Add(new JqGridRecord(Convert.ToString(invoiceGrid.Id), invoiceGrid));
            //}

            //response.Reader.RepeatItems = false;

            //return new JqGridJsonResult(response);
            return View();
        }

        [HttpGet]
        public string GetInvoiceLastDate(int iValue,string company)
        {
            string userName = HttpContext.Session.GetString("UserName");
            string databaseName = HttpContext.Session.GetString("Database_Name");
            string dLastInvoiceDate = _invoicGeneration.GetLastInvoiceDateQuery(-1,databaseName,company);
            
            return dLastInvoiceDate;
        }
    }
}

Telecom.WebUI/Views/Invoice/InvoiceTab/_InvoiceGrid.cshtml
@model List<Telecom.Application.ViewModels.InvoiceGrid>


<table id="tblInvoiceGrid">
    <tbody>
        @foreach (var invoiceGrid in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" value="@invoiceGrid.AddressNbr" id="check@(invoiceGrid.AddressNbr)"  checked />
                </td>
                <td><label for="check@(invoiceGrid.AddressNbr)">@invoiceGrid.AddressNbr--@invoiceGrid.Name--@invoiceGrid.BillCycle</label></td>
            </tr>
        }
    </tbody>
</table>

Telecom.WebUI/Views/Invoice/InvoiceTab/_InvoiceOptions.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<script>
    $(document).ready(function () {
        $('#InvoicGrouping').on('change', function () {
            if ($(this).is(":checked")) {
                $('#ShowNoInvoice').prop('disabled', false);
            }
            else {
                $('#ShowNoInvoice').prop('disabled', true);
            }
                
        });
    });
</script>
<div class="row">
    <div class="col-sm-6">
        <input type="checkbox" id="CallsData" checked="checked" name="CallsData" value="Calls/Data" />
        <label for="CallsData"><b>Calls/Data</b></label>
    </div><br />
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="checkbox" checked="checked" name="GeneralItems" id="GeneralItems" value="General Items" />
        <label for="GeneralItems"><b>General Items</b></label>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="checkbox" checked="checked" name="CallDiscounts" id="CallDiscounts" value="Call Disocunts" />
        <label for="CallDiscounts"><b>Call Disocunts</b></label>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="checkbox" checked="checked" name="InvoicGrouping" id="InvoicGrouping" value="Invoice Grouping" />
        <label for="InvoicGrouping"><b>Invoice Grouping</b></label>
        <div id="divShowNoInvoice">
            <input type="checkbox" checked="checked" name="ShowNoInvoice" id="ShowNoInvoice" value="Show no Invoice" />
            <label for="ShowNoInvoice"><b>Show no Invoice</b></label>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="checkbox" checked="checked" name="CreateBankFile" id="CreateBankFile" value="Create Bank file" />
        <label for="CreateBankFile"><b>Create Bank file</b></label>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="checkbox" checked="checked" name="CreateZeroInvoices" id="CreateZeroInvoices" value="Create Zero invoices" />
        <label for="CreateZeroInvoices"><b>Create Zero invoices</b></label>
    </div>
</div>
<div class="row">
    <div class="col-sm-8">
        <input type="checkbox" name="ShowInvoicegroupCustomerOnReport" id="ShowInvoicegroupCustomerOnReport" value="Show Invoicegroup/Customer on report" />
        <label for="ShowInvoicegroupCustomerOnReport"><b>Show Invoicegroup/Customer on report</b></label>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <input type="checkbox" name="AssignAutomaticalyPayments" id="AssignAutomaticalyPayments" value="Assign automaticaly payments" />
        <label for="AssignAutomaticalyPayments"><b>Assign automaticaly payments</b></label>
    </div>
</div>

Telecom.WebUI/Views/Invoice/InvoiceTab/_PrintOptions.cshtml
@model Telecom.Application.ViewModels.InvoicingSelectionViewModel;
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="row">
    <div class="col-sm-6">
        <b>Print Type</b>
        @Html.DropDownListFor(x=>x.SelectedInvoiceOption,new SelectList(Model.InvoiceOption,"Value","Text"),
               htmlAttributes:new {@class="form-control",id= "InvoiceCallPrintType" })
        @Html.ValidationMessageFor(x => x.SelectedInvoiceOption, "", new { @class = "text-danger" })
    </div>
    <div class="col-sm-6">
        <input type="checkbox" checked="checked" name="CallsData" value="Exclude Mobile" id="CallsData"/> 
        <label for="CallsData"><b>Exclude Mobile</b></label>
    </div>
</div>
<br />
<div class="container" style="background-color:aliceblue">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-8">
            <div class="tab">
                <div id="priorityscroll">
                    <ul class="nav nav-tabs tab" id="MyTabs">
                        <li id="liSelection" class="active"><a class="active" role="tab" data-toggle="tab" href="#tabInvoiceMemo">Invoice Memo</a></li>
                        <li id="liInvoiceOptions" class=""><a role="tab" data-toggle="tab" href="#tabInvoiceMemoPrefix">Invoice Memo/Prefix</a></li>
                    </ul>
                    <div class="tab-content tabs">
                        <div role="tabpanel" id="tabInvoiceMemo" class="tab-pane fade active show">
                        </div>
                        <div role="tabpanel" id="tabInvoiceMemoPrefix" class="tab-pane fade">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Telecom.WebUI/Views/Invoice/InvoiceTab/_Selection.cshtml
@model Telecom.Application.ViewModels.InvoicingSelectionViewModel;

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-sm-12">
                    <b>InvoiceType :</b>
                    @*@Html.RadioButtonFor()*@
                    @foreach (var invoicingType in Model.InvoiceType)
                    {
                        if (@invoicingType == "Invoicing")
                        {
                            <input type="radio" asp-for="SelectedInvoiceType" value="@invoicingType" id="Invice@(invoicingType)" checked />
                            <label for="Invice@(invoicingType)">@invoicingType :</label>
                        }
                        else
                        {
                            <input type="radio" asp-for="SelectedInvoiceType" value="@invoicingType" id="Invice@(invoicingType)"/>
                            <label for="Invice@(invoicingType)">@invoicingType :</label>
                        }

                    }
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <label id="lblBillingCycle"><b>Bill cycle :</b></label>
                    <input asp-for="BillingCycle" class="form-control" />
                </div>
            </div>
            <div class="row">
                <b>Company</b>
                @Html.DropDownListFor(x=>x.SelectedCompany,new SelectList(Model.Company,"Value","Text"),
               htmlAttributes:new { @class="form-control",id="Company"})
                @Html.ValidationMessageFor(x => x.SelectedCompany, "", new { @class = "text-danger" })
            </div>
            <div class="row">
                <b>Invoice creation options :</b>
                @Html.DropDownListFor(x=>x.SelectedInvoiceOption,new SelectList(Model.InvoiceOption,"Value","Text"),
               htmlAttributes:new {@class="form-control",id="InvoiceOption" })
                @Html.ValidationMessageFor(x => x.SelectedInvoiceOption, "", new { @class = "text-danger" })
            </div>
            <div class="row">
                <div class="col-sm-9">
                    <b>From: </b>
                    <div>
                        <input asp-for="FromFilter"/>
                    </div>
                    <b>To:</b>
                    <div>
                        <input asp-for="ToFilter" />
                    </div>
                </div>
                <div class="col-sm-3">
                    <button id="find" class="btn btn-success">Find</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-9">
                    Active:
                    <div>
                        @foreach (var item in Model.Action)
                        {
                            if (@item == "Check")
                            {
                                <input type="radio" value="@item" asp-for="SelectedAction" id="Action@(item)" checked />@item
                            }
                            else
                            {
                                <input type="radio" value="@item" asp-for="SelectedAction" id="Action@(item)" />@item
                            }

                        }

                    </div>
                </div>
                <div class="col-sm-3">
                    <button id="Save" class="btn btn-success">Save</button>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-sm-10">
                    <input type="checkbox" value="MaxDate" asp-for="ExcludePricingFrom" />
                    <label for="ExcludePricingFrom"><b>Execlude pricings as from:</b></label>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Month"><b>Month: </b> </label>
                </div>
                <div class="col-sm-3">
                    <input asp-for="Month" />
                </div>
                <div class="col-sm-2">
                    <label asp-for="Year"><b>Year:</b> </label>
                </div>
                <div class="col-sm-3">
                    <input asp-for="Year" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <b>Create Invoice Options</b>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="InvoiceDate"><b>Invoice Date: </b></label>
                </div>
                <div class="col-sm-6">
                    <input asp-for="InvoiceDate" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-10">
                    <input type="checkbox" asp-for="GenerateRecurringInvoice" checked="checked" />
                    <label for="GenerateRecurringInvoice"><b>Generate Recurring Invoice</b></label>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <input type="checkbox" asp-for="GenerateOneOffInvoice" id="GenerateOneOffInvoice" value="GenerateOneOffInvoice"/>
                    <label for="GenerateOneOffInvoice"><b>Generate OneOff Invoice</b></label>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <b>Find user in customer list</b>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <input asp-for="FindCustomer" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-6">
                    <input type="submit" id="btnSelectAll" value="Select all" class="btn btn-success" />
                </div>
                <div class="col-sm-6">
                    <input type="submit" id="btnUnSelectAll" value="Unselect all" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#Company').on("change", function () {
            //alert(this.value);
            var bilCycle = $('#BillingCycle').val();
            if (bilCycle == undefined || bilCycle == "") {
                alert('Bill cycle not be blank');
                $('#Company').val('');
                return;
            }
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetInvoice", "Invoice")',
                data: {
                    companyName: "ACN AT",
                    checkRecurringInvoice: true,
                    billingCycle: "23",
                    chbExcludeMobile: true
                    },
                contentType: "application/json; charset=utf-8",
                dataType: "html",
                success: function (data) {
                  //  alert('Success');
                    $("#invoiceList").html(data);
                }
                ,
                failure: function (data) {
                    alert(data.responseText);
                },//End of AJAX failure function
                error: function (xhr) {
                    alert('error');
                }//End of AJAX Error function
            });
        });

        $('#BillingCycle').on("change", function () {
            //alert(this.value);
            if (this.value < 1 || this.value > 31) {
                $('#BillingCycle').val('23');
                alert('wrong billing Cycle value');
                return;
            }
        })

        $('#btnUnSelectAll').on('click', function () {
            $('tbody tr td input[type="checkbox"]').each(function () {
                $(this).prop('checked', false);
            });
        });

        $('#btnSelectAll').on('click', function () {
            $('tbody tr td input[type="checkbox"]').each(function () {
                $(this).prop('checked', true);
            });
        });

        $('#find').on('click', function () {
            var fromValue = $('#FromFilter').val();
            
            var toValue = $('#ToFilter').val();
            
            var activeStatus = null,disactiveStatus;
            if ($('#ActionCheck').is(':checked')) {
                activeStatus = true;
            } else
                activeStatus = false;

            if (activeStatus)
                disactiveStatus = false;
            else
                disactiveStatus = true;

            $('tbody tr td input[type="checkbox"]').each(function () {
                
                if ($(this).val() >= fromValue && $(this).val() <= toValue) {

                    $(this).prop('checked', activeStatus);
                } else {
                    $(this).prop('checked', disactiveStatus);
                }
            });


        });
    })
</script>